#!/usr/bin/env bash
# Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.

if [ -f apache-access\ \(1\).log ];
then
	awk -F" " '{ print $1, $9}' apache-access\ \(1\).log 
else
	exit 1
fi
