#!/usr/bin/env bash
# This script use if condint in while loop.

x=1
while [ $x -le 20 ]
do
	case $x in
		4)
			echo -e "$x\nbad luck from China"
			;;
		9)	
			echo -e "$x\nbad luck from Japan"
			;;
		17)
			echo -e "$x\nBad luck from Italy"
			;;
		*)
			echo "$x"
			;;
	esac
	x=$(( x +1 ))
done
