#!/usr/bin/env bash
# Script that displays:
	# The content of the current directory
	# In a list format
	# Where only the part of the name after the first dash is displayed (refer to the example)

ls=$(ls ./ | cut -d "-" -f2)
for i in $ls
do
	echo "$i"
done
